name: Build AAB for Android

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: true
        default: production
        type: choice
        options:
          - production
          - preview

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install EAS CLI
        run: npm install -g eas-cli
      
      - name: Verify Expo Login
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      
      - name: Build AAB
        run: eas build --platform android --profile ${{ github.event.inputs.build_type }} --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
